"""Historical static Bullet Cluster illustration, not an observational stress test.

Gas, stellar and entropy fields are prescribed analytic shapes. The entropy
suppression is an assumed weighting, and the maps are normalized to their own
maxima. No measured maps, dynamical collision, entropy-production equation or
derived lensing field equation is evaluated. Numerical outputs are retained for
illustration, but cannot establish a pass/failure for EMRF or MOND.
"""

from __future__ import annotations

import dataclasses

import numpy as np

# Observational parameters of 1E 0657-56 (Clowe et al. 2006, Markevitch 2006)
CLUSTER_SEPARATION_KPC: float = 500.0   # Main vs Subcluster separation
SHOCK_TEMP_KEV: float = 14.8            # Bullet shock temperature ~1.7e8 K
PRE_SHOCK_TEMP_KEV: float = 7.0         # Pre-shock temperature ~8e7 K
OBSERVED_OFFSET_KPC: float = 215.0      # Spatial offset between X-ray gas and lensing peak


@dataclasses.dataclass
class BulletClusterSimulation:
    """2D spatial grid representation of the Bullet Cluster collision plane."""
    grid_size_kpc: float = 600.0
    resolution: int = 121               # 121x121 grid

    def __post_init__(self):
        self.coords = np.linspace(-self.grid_size_kpc, self.grid_size_kpc, self.resolution)
        self.X, self.Y = np.meshgrid(self.coords, self.coords)

    def generate_baryonic_distributions(self) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Generate 2D surface mass density for X-ray gas and stellar galaxies.

        Returns: (sigma_gas, sigma_stars, sigma_baryon_total) in arbitrary M_sun/kpc^2 units.
        """
        # Gas peaks: decelerated by ram pressure, centered near x = -50 kpc and x = +50 kpc
        # Subcluster bullet gas is compressed at x = +120 kpc
        gas_main = 0.60 * np.exp(-((self.X + 60.0)**2 + self.Y**2) / (2.0 * 90.0**2))
        gas_bullet = 0.25 * np.exp(-((self.X - 110.0)**2 + self.Y**2) / (2.0 * 50.0**2))
        sigma_gas = gas_main + gas_bullet

        # Stellar galaxy clumps: collisionless, passed through to x = -250 kpc and x = +240 kpc
        stars_main = 0.10 * np.exp(-((self.X + 260.0)**2 + self.Y**2) / (2.0 * 70.0**2))
        stars_bullet = 0.05 * np.exp(-((self.X - 240.0)**2 + self.Y**2) / (2.0 * 45.0**2))
        sigma_stars = stars_main + stars_bullet

        sigma_baryon_total = sigma_gas + sigma_stars
        return sigma_gas, sigma_stars, sigma_baryon_total

    def generate_entropy_field(self) -> np.ndarray:
        """Compute the 2D thermodynamic entropy field S(X,Y).

        Thermal entropy per particle in plasma: s ~ ln(T^(3/2) / rho).
        In the shock front (x ≈ +150 kpc to +200 kpc) and central collisional zone,
        turbulent thermal entropy is intensely elevated (S ~ 5 - 10),
        whereas collisionless stellar clumps have low thermal entropy (S ~ 0.1).
        """
        # Baseline entropy
        s_base = 0.2
        # Shock-heated turbulent entropy in collisional zone
        s_shock = 8.5 * np.exp(-((self.X - 40.0)**2 + self.Y**2) / (2.0 * 120.0**2))
        s_bullet_bow = 9.0 * np.exp(-((self.X - 140.0)**2 + self.Y**2) / (2.0 * 40.0**2))
        entropy_field = s_base + s_shock + s_bullet_bow
        return entropy_field

    def compute_naive_mond_lensing_convergence(self) -> np.ndarray:
        """Naive modified gravity: lensing potential directly traces total baryonic surface mass.

        kappa_naive(x,y) ~ sqrt(sigma_baryon_total).
        """
        _, _, sigma_bar = self.generate_baryonic_distributions()
        kappa = np.sqrt(sigma_bar)
        kappa /= np.max(kappa)
        return kappa

    def compute_emrf_entropy_compression_convergence(
        self,
        entropy_coupling_beta: float = 0.45,
    ) -> np.ndarray:
        """Evaluate the historical assumed entropy-weighted illustration.

        C = sigma_stars/(1 + beta*0.2) + sigma_gas/(1 + beta*S_gas)^2.2.
        The exponent 2.2 is retained, not derived. S_gas is prescribed, not
        generated by compression dynamics. The returned sqrt(C)/max(sqrt(C))
        is dimensionless and is not an absolute lensing-convergence prediction.
        """
        sigma_gas, sigma_stars, _ = self.generate_baryonic_distributions()
        entropy_field = self.generate_entropy_field()

        # Coherent stellar compression: low internal entropy
        c_stars = sigma_stars / (1.0 + entropy_coupling_beta * 0.2)
        # Gas compression: strongly suppressed by high turbulent thermal entropy
        c_gas = sigma_gas / ((1.0 + entropy_coupling_beta * entropy_field) ** 2.2)

        c_total = c_stars + c_gas
        # Effective surface mass / convergence
        kappa = np.sqrt(c_total)
        kappa /= np.max(kappa)
        return kappa

    def find_peak_centroids(
        self, kappa_map: np.ndarray
    ) -> tuple[tuple[float, float], tuple[float, float]]:
        """Find the coordinates (x, y) in kpc of the main and bullet peaks."""
        # Main peak (left hemisphere: x < -20 kpc)
        mask_main = self.X < -20.0
        sub_main = np.where(mask_main, kappa_map, -1.0)
        idx_main = np.unravel_index(np.argmax(sub_main), kappa_map.shape)
        main_peak = (float(self.X[idx_main]), float(self.Y[idx_main]))

        # Bullet peak (right hemisphere: x > 50 kpc)
        mask_bullet = self.X > 50.0
        sub_bullet = np.where(mask_bullet, kappa_map, -1.0)
        idx_bullet = np.unravel_index(np.argmax(sub_bullet), kappa_map.shape)
        bullet_peak = (float(self.X[idx_bullet]), float(self.Y[idx_bullet]))

        return main_peak, bullet_peak


def evaluate_bullet_cluster_stress_test() -> dict[str, dict]:
    """Return illustrative offsets with explicit non-empirical evidence status."""
    sim = BulletClusterSimulation()
    sigma_gas, _, sigma_bar = sim.generate_baryonic_distributions()

    # Gas peak locations (baryon ground truth)
    gas_main_peak, gas_bullet_peak = sim.find_peak_centroids(sigma_gas)

    # 1. Naive MOND
    kappa_naive = sim.compute_naive_mond_lensing_convergence()
    naive_main, naive_bullet = sim.find_peak_centroids(kappa_naive)
    offset_naive = abs(naive_bullet[0] - gas_bullet_peak[0])

    # 2. EMRF Entropy Compression
    kappa_emrf = sim.compute_emrf_entropy_compression_convergence()
    emrf_main, emrf_bullet = sim.find_peak_centroids(kappa_emrf)
    offset_emrf = abs(emrf_bullet[0] - gas_bullet_peak[0])

    return {
        "evidence": {
            "kind": "synthetic_static_illustration",
            "observations_ingested": False,
            "entropy_is_an_input": True,
            "entropy_production_computed": False,
            "absolute_lensing_prediction": False,
            "reason": "No observational likelihood or derived dynamical prediction",
        },
        "gas_peaks": {"main": gas_main_peak, "bullet": gas_bullet_peak},
        "naive_mond": {
            "main_peak": naive_main,
            "bullet_peak": naive_bullet,
            "offset_from_gas_kpc": offset_naive,
            "illustrative_offset_exceeds_100_kpc": offset_naive >= 100.0,
            "matches_observation": None,
            "status": "NOT TESTED (prescribed baryonic proxy, not a MOND field solution)",
        },
        "emrf_entropy_compression": {
            "main_peak": emrf_main,
            "bullet_peak": emrf_bullet,
            "offset_from_gas_kpc": offset_emrf,
            "illustrative_offset_exceeds_100_kpc": offset_emrf >= 100.0,
            "matches_observation": None,
            "status": "NOT TESTED (assumed entropy weighting, not an empirical EMRF prediction)",
        },
    }


if __name__ == "__main__":
    report = evaluate_bullet_cluster_stress_test()
    print("=" * 80)
    print("BULLET CLUSTER STATIC ILLUSTRATION -- NO OBSERVATIONAL VALIDATION")
    print("=" * 80)
    print(f"X-ray Gas Bullet Peak: {report['gas_peaks']['bullet'][0]:.1f} kpc")
    for key in ("naive_mond", "emrf_entropy_compression"):
        row = report[key]
        print(f"{key}: peak {row['bullet_peak'][0]:.1f} kpc | "
              f"offset {row['offset_from_gas_kpc']:.1f} kpc | {row['status']}")
    print("=" * 80)
